# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoriCrawlerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawler',
            options={'ordering': ('crawler_name', 'crawler_id')},
        ),
        migrations.RenameField(
            model_name='crawler',
            old_name='name',
            new_name='crawler_name',
        ),
        migrations.AddField(
            model_name='crawler',
            name='crawler_id',
            field=models.CharField(default='HYU', max_length=100),
            preserve_default=False,
        ),
    ]
