# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoriCrawlerAPI', '0003_auto_20160911_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('user_id', 'crawler_id')},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='crawler_name',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='latest_pushtime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
